version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run: echo "build project"
      - npm install
      - npm run build
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - build
