version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
        name: Install Dependencies
        command: yarn install --immutable
      - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test
      - run: 
          name: Build dashboard
          command: yarn dev

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
